# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - binary: genderize
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  # this name template makes the OS and Arch compatible with the results of uname.
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}{{ with .Arm }}v{{ . }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^ci:"
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: karlderkaefer
      name: homebrew-tap
    directory: Formula
    name: genderize
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    custom_require: ../lib/custom_downloader.rb
    description: Example CLI tool written in Go
    license: MIT
    test: |
      system "#{bin}/genderize -v"
